### ISSUE TITLE
Decision on entrypoint to use

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [ec-jrc/Thalassa#13]
Right now the code has 3 entry points:
- thalassa/main.py
- Thalassa.ipynb
- thalassa/cli.py

This can be confusing to get started with Thalassa. It would be nice if these could be consolidated into one.
Ideally instead of being static, the cli script would read a config file (e.g. xml, yaml, etc) to define what pages/apps to include.

**Comment by pmav99** [comment]
The truth is that it is quite confusing.

A bit of backrgound:

> Thalassa is based on work that @brey did during the past couple of years when he experimented with pretty much all the visualization libraries in the Python ecosystem. I started working on it when I first started to collaborate with George about a year ago. At the time I had a short term contract and we were working on other stuff too, so there was not a lot of time to do things properly. Furthermore there were problems with *where* to deploy it. No need to bore you with all the details, but the end result was that among other things we also did try to get thalassa to run on binder, too (using conda). Unfortunately that was a failure so in the end we did deploy it on a random VPS using docker just to be able to show it to you guys

Nevertheless, there was no time to clean things up... That's why it is such a mess

Now, to go to the gist of the issue.

> Disclaimer: I am not an expert in the holoviews/bokeh ecosystem. I've only used it in the context of thalassa. 

My understanding is that in theory, the `panel.serve()` function is the proper way to serve multiple endpoints (e.g. `/elevation`, `/forecast` etc). That's what [awesome-panel](https://github.com/MarcSkovMadsen/awesome-panel/blob/b1f2668b485c4889666039668588726f0652f4bc/app.py#L28-L31) is using afteral. Nevertheless, `panel.serve()` has problems with multiple workers and `datashade`; probably something related to numba. There is an open issue for that: https://github.com/holoviz/panel/issues/1720 but this is a deal breaker for us. We need datashade and in order to have acceptable performance we need multiple workers.

That's why in version 0.2 I suggest that we use `panel serve` instead (which AFAIK is just a thin wrapper around `bokeh serve`). If we need to serve multiple endpoints with `panel serve`, I belieive it is possible to do that too by creating multiple entrypoints (e..g `foo.py` and `goo.py`) and serve both of them using a single panel/bokeh server with  `panel serve ./foo.py ./goo.py`

Other that that, panel serve does support `--num-procs` which is needed for deployment and `--autoreload` which is useful for developing. 

The integration with jupyter is something that we get for free and which can be useful when developing. Nevertheless, I don't think we need to have it as an official way of running thalassa.

**Comment by SorooshMani-NOAA** [comment]
Thank you for the information on the history of the development. 

I was not aware of the issues with `panel.serve()`. The thing that I noticed though is that `panel serve` at least in my tests starts a server which itself starts new separate Bokeh server's upon connection to the url. This make things less useful when deploying on a remote machine since we might want to just tunnel a specific port out of that machine and having new servers on new ports breaks the workflow. To be concrete:
- I connect to a remote machine and map port PANEL_PORT to my machine port (let's call it FWD_PORT)
- I run `panel serve Thalassa.ipynb` on the remote machine
- When on the local machine I connect to `localhost:FWD_PORT` it shows an empty page

If I try the same setup on a local machine (no remote machine involved) what happens is that when I connect to  `localhost:LOCAL_PORT` I see that the browser automatically opens a new tab with a server on a different port. To me it seems that the main server just spawned off a new server to handle page for a given client, instead of directly serving the client.

Does `panel serve` allow us to specify using a single Bokeh server?

**Comment by pmav99** [comment]
Mmm... you are probably missing the `--allow-websocket-origin` argument. 

Just to make sure we are on the same page:

### SSH tunnel

First of Create an SSH tunnel that maps a LOCAL_PORT to a REMOTE_PORT. 

You need something like this: `ssh -L ${LOCAL_PORT}:localhost:${REMOTE_PORT} user@server`

`LOCAL_PORT` and `REMOTE_PORT` can have the same value. E.g. they can both be 5006 since they refer to different hosts. Nevertheless, in order to make things more transparent let's say that the LOCAL_HOST is 55555 and that the remote port is the default bokeh port, i.e. 5006. This means that the command you need to run is 

`ssh -L 55555:localhost:5006 user@server`

## Run the panel server on the remote host

```
panel serve ./thalassa --log-level debug
```

## Check connection on your PC

```
curl localhost:55555/thalassa
```

This should show you the HTML code. This means that the SSH tunnel works and that the requests are reaching the webserver on the remote host. 

Nevertheless, if you open the `localhost:55555/thalassa` on your browser you should indeed see an empty web page. Now open the development tools on your browser (usually F12). Go to the console or to the network tab and refresh the page. you should see an error similar to this: `Firefox can’t establish a connection to the server at ws://localhost:15006/thalassa/ws.` 

## How to fix it?

Go back to the console running `panel` on the remote host. Stop the server from running and restart it with:

``` 
panel serve ./thalassa --log-level debug --allow-websocket-origin '*'
```

## Hints

- When refreshing the browser remember to hit Ctrl + F5 to avoid issues with browser caching
- Using ` --allow-websocket-origin '*'` is a security risk. Instead of the wildcard you should use something more specific (e.g. the IP:PORT of your reverse proxy or of your SSH tunnel.
- The rendering might take 2 or 3 times more compared to your local PC (servers have slower CPUs/disks + there is the network overhead)

**Comment by SorooshMani-NOAA** [comment]
Thank you for the detailed debugging info. However my issue was not `allow-websocket-origin`. What I see is related to `panel` opening a new server for every connection to the original server. I haven't tested it with the v0.2 yet, but in v0.1 I saw this issue when trying 
```
panel serve ./Thalassa.ipynb --allow-websocket-origin '*'
```

Maybe that's just an issue with serving notebooks then.

**Comment by pmav99** [comment]
> . The thing that I noticed though is that panel serve at least in my tests starts a server which itself starts new separate Bokeh server's upon connection to the url

Are you sure about this?

If I start a single panel server with 4 workers we get a master process which spawns 4 other processes listening on the same port
```
$ panel serve --num-procs 4 ./thalassa --port 9999
2021-10-07 22:20:05,664 Starting Bokeh server version 2.4.0 (running on Tornado 6.1)
2021-10-07 22:20:05,665 User authentication hooks NOT provided (default user enabled)
2021-10-07 22:20:05,671 Bokeh app running at: http://localhost:9999/thalassa
2021-10-07 22:20:05,671 Starting Bokeh server with process id: 191100
2021-10-07 22:20:05,673 Bokeh app running at: http://localhost:9999/thalassa
2021-10-07 22:20:05,673 Starting Bokeh server with process id: 191101
2021-10-07 22:20:05,675 Bokeh app running at: http://localhost:9999/thalassa
2021-10-07 22:20:05,675 Starting Bokeh server with process id: 191102
2021-10-07 22:20:05,676 Bokeh app running at: http://localhost:9999/thalassa
2021-10-07 22:20:05,676 Starting Bokeh server with process id: 191103
```
```
$ pstree -hp $(pgrep -f panel | sort | head -n1)
panel(191081)─┬─panel(191100)
              ├─panel(191101)
              ├─panel(191102)
              └─panel(191103)
```

The fact that no other port is involved can be shown with:
```
$ sudo ss -tunlp  | ag panel
tcp   LISTEN 0      128               0.0.0.0:5006       0.0.0.0:*    users:(("panel",pid=191103,fd=3),("panel",pid=191102,fd=3),("panel",pid=191101,fd=3),("panel",pid=191100,fd=3),("panel",pid=191081,fd=3))
tcp   LISTEN 0      128                  [::]:5006          [::]:*    users:(("panel",pid=191103,fd=4),("panel",pid=191102,fd=4),("panel",pid=191101,fd=4),("panel",pid=191100,fd=4),("panel",pid=191081,fd=4))
```

**Comment by pmav99** [comment]
> Maybe that's just an issue with serving notebooks then

I haven't tested serving notebooks. Nevertheless, the console and the network tab in the dev tools should give you some hints.

**Comment by SorooshMani-NOAA** [comment]
I need to retest, that was my understanding based on my observations last time.

**Comment by pmav99** [comment]
@SorooshMani-NOAA is there anything else or can we close the issue? I think that the original issue is now obsolete

**Comment by SorooshMani-NOAA** [comment]
@pmav99 Sorry for my late reply. Yes this issue is not relevant anymore.
