### ISSUE TITLE
Question about support for SCHISM output file

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [ec-jrc/Thalassa#40]
I've been trying to use Thalassa (`master` branch) on some SCHISM combined output `.nc` files, but I keep on getting out of bound index error. The SCHISM solution is on a completely triangular mesh (no mixed elements). Is SCHISM output supported out of the box, or first I need to reindex the `.nc` files? (e.g 0-based vs 1-based indexing)

**Comment by wzhengui** [comment]
Can you try this branch https://github.com/ec-jrc/Thalassa/tree/add_variables, and let me know whether you get the same error?

**Comment by brey** [comment]
This was a bug that was supposed to be fixed with our original PR but that has now been superseded by @wzhengui 's PR. I don't know if this is fixed there. So something like this should work.

 https://github.com/brey/Thalassa/blob/23596b9d148cfdbfb76f1726949dae867ada1ef0/thalassa/api.py#L96-L97

**Comment by wzhengui** [comment]
Hi @brey: 

It was fixed in my PR. Here is the complete description of my PR. 

1). improve the Thalassa UI by adding necessary widgets and removing unnecessary widgets
2). improve the Thalassa structure, which I thinks makes it more organized, more extendable to include other models. To add another model, one just needs: a). add datasets read method (utils.py), and b). add the corresponding plot method in "api.py"
3). resolve the loading issue for large-size file
4). support transformation of different projection
5). support to show more SCHISM variables (2D, 3D, and 4D variables).
6). support native SCHISM outputs (schout_*.nc). No need for pro-processing
7). Support triangle and quadrilaterals (quads are split into two triangles).

**Comment by SorooshMani-NOAA** [comment]
Thank you @brey and @wzhengui for your responses. I haven't had time to test this on the pull request branch. I wanted to make sure I'm not setting up anything else incorrectly. The next time I try it, I'll test the pull request branch.

**Comment by pmav99** [comment]
Both zero-based and one-based indexes are supported in the current master.
