### ISSUE TITLE
Visualizing Global Meshes

### ISSUE THREAD

**Issue by pmav99** [ec-jrc/Thalassa#58]
This is something that came up after investigating why the STOFS 2D Global model could not be visualized (#54). STOFS is an ADCIRC model, but the same problem should exist for SCHISM models, too, therefore I think that we should have a dedicated issue.

So, visualizing the STOFS model gives this output:

![image](https://user-images.githubusercontent.com/411196/226213785-2a19f0c5-a30e-4089-8af4-a7d17e1fc7e3.png)

The problem is that there are elements crossing over the international time line and this messes up the visualization. The white line at ~65 latitude is because at that particular range the international line crosses the region North of Kamtchatka (not sure of the actual name).  

This problem is something that we have encountered before while trying to visualize global meshes and pyposeidon does provide a fix for this and the [docs](https://pyposeidon.readthedocs.io/en/latest/utils.html#seam) do explain in a bit more detail. Applying the fix though takes significant time. So you need to do it a post-processing step. You can't do it dynamically in thalassa. At least not for these 12 million nodes files.

@brey can provide more details if necessary.

pinging @saeed-moghimi-noaa

**Comment by josephzhang8** [comment]
A simple fix is to remove all elements that straddle across the dateline. We have simple fort script to do that; see schism src code:

src/Utility/Grid_Scripts/spherical_remove_wraparound.f90


Regards,
-------------------------------
Joseph Zhang
(804)684 7595 (office)

SCHISM web: http://ccrm.vims.edu/schism/
From: pmav99 ***@***.***>
Sent: Sunday, March 19, 2023 7:01 PM
To: ec-jrc/Thalassa ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ec-jrc/Thalassa] Visualizing Global Meshes (Issue #58)


[EXTERNAL to VIMS received message]


This is something that came up after investigating why the STOFS 2D Global model could not be visualized (#54<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fec-jrc%2FThalassa%2Fissues%2F54&data=05%7C01%7Cyjzhang%40vims.edu%7Ced00c2210aa6464e591508db28cdc242%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C638148636437862418%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wf%2Bs8Sj95U8q6VxqA%2FqlTL5pROlBN1S0x%2BjAI%2B4PIAo%3D&reserved=0>). STOFS is an ADCIRC model, but the same problem should exist for SCHISM models, too, therefore I think that we should have a dedicated issue.

So, visualizing the STOFS model gives this output:

[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F411196%2F226213785-2a19f0c5-a30e-4089-8af4-a7d17e1fc7e3.png&data=05%7C01%7Cyjzhang%40vims.edu%7Ced00c2210aa6464e591508db28cdc242%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C638148636437862418%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4t0Hppmq%2Fz4NekuiQBt8bBEElRZPZWHz1URk7d4YkgQ%3D&reserved=0>

The problem is that there are elements crossing over the international time line and this messes up the visualization. The white line at ~65 latitude is because at that particular range the international line crosses the region North of Kamtchatka (not sure of the actual name).

This problem is something that we have encountered before while trying to visualize global meshes and pyposeidon does provide a fix for this and the docs<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpyposeidon.readthedocs.io%2Fen%2Flatest%2Futils.html%23seam&data=05%7C01%7Cyjzhang%40vims.edu%7Ced00c2210aa6464e591508db28cdc242%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C638148636437862418%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5pYF6vucQk4sYS0jMIO%2FoY%2F%2Fh%2B%2BZ3hU%2BKfoUPnF6vFo%3D&reserved=0> do explain in a bit more detail. Applying the fix though takes significant time. So you need to do it a post-processing step. You can't do it dynamically in thalassa. At least not for these 12 million nodes files.

@brey<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrey&data=05%7C01%7Cyjzhang%40vims.edu%7Ced00c2210aa6464e591508db28cdc242%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C638148636437862418%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4xQZkIwaxS%2F9g5GZRA5rfbV1u6AeiBYYB3So75v2A4A%3D&reserved=0> can provide more details if necessary.

pinging @saeed-moghimi-noaa<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsaeed-moghimi-noaa&data=05%7C01%7Cyjzhang%40vims.edu%7Ced00c2210aa6464e591508db28cdc242%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C638148636437862418%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Z5mDFpTmMZ54xQa5IhdNB5wazHz3EHapcuDFnwF%2Bb3U%3D&reserved=0>

-

**Comment by brey** [comment]
FYI, the tool that `pyposeidon` offers is described in the [docs](https://pyposeidon.readthedocs.io/en/latest/utils.html) and in the [Tutorial](https://github.com/ec-jrc/pyPoseidon/blob/master/Tutorial/UTILS.ipynb). Note however that the script is `SCHISM` specific and it needs to be generalised/modified.

**Comment by pmav99** [comment]
A pure-python implementation for dropping the elements that cross the IDL (i.e. Joseph's suggestion) is the following:
``` python
def drop_elements_crossing_idl(ds: xr.Dataset, max_lon: float = 100) -> xr.Dataset:
    """
    Drop triface elements crossing the International Date Line (IDL).
    
    ``max_lon`` is the maximum longitudinal "distance" in degrees for an element.
    """
    if max_lon <= 0:
        raise ValueError(f"Maximum longitudinal \"distance\" must be positive: {max_lon}")
    a, b, c = ds.triface_nodes.T
    indices_of_triface_nodes_crossing_idl = np.where(
          (np.abs(ds.lon[a] - ds.lon[b]) > max_lon)
        | (np.abs(ds.lon[a] - ds.lon[c]) > max_lon)
        | (np.abs(ds.lon[b] - ds.lon[c]) > max_lon)
    )[0]
    ds = ds.drop_isel(triface=indices_of_triface_nodes_crossing_idl)
    return ds
```

It can be used like this:
``` python
from thalassa import api

ds  = api.open_dataset("/path/to/output.nc")
ds = drop_elements_corssing_idl(ds=ds)

# use the normal api functions ...
```

We could add this functionality in thalassa but is relatively slow for big meshes (30+ seconds on my laptop). I don't think it is something that we want to be using interactively. IMHV this belongs to the post-processing steps of a model.

**Comment by pmav99** [comment]
For the record, this is a faster, but also more memory intensive implementation (my laptop run out of memory when I run this on the STOFS output):
``` python
def drop_elements_crossing_idl2(ds: xr.Dataset, max_lon: float = 100) -> xr.Dataset:
    """
    Drop triface elements crossing the International Date Line (IDL).
    
    ``max_lon`` is the maximum longitudinal "distance" in degrees for an element.
    """
    if max_lon <= 0:
        raise ValueError(f"Maximum longitudinal \"distance\" must be positive: {max_lon}")
    indices_of_triface_nodes_crossing_idl = np.where(
        np.abs(ds.lon[ds.triface_nodes] - ds.lon[ds.triface_nodes.roll(three=1)]) > max_lon
    )[0]
    ds = ds.drop_isel(triface=indices_of_triface_nodes_crossing_idl)
    return ds
```

**Comment by pmav99** [comment]
In the end, I added in utils.py a function that drops elements that cross the IDL: 
https://github.com/ec-jrc/Thalassa/blob/3dcc1b4cfb8bd5fa4ad7974a2af8d6762f082f5c/thalassa/utils.py#L119-L159

With the current implementation there are false positives, i.e. close to the poles, even elements that don't cross the IDL may be dropped. Nevertheless, it is quite fast and it should be good enough for a quick check of the results.

Closing
