### ISSUE TITLE
docs: Visualizing maximum elevation from SCHISM

### ISSUE THREAD

**Issue by FariborzDaneshvar-NOAA** [ec-jrc/Thalassa#73]
I'm using API to visualize elevation outputs from SCHISM. 
The `timestamp` enables the user to select a specific time for `create_trimesh()` function (i.e. '2011-08-05T22:00:00.000000000' or max which is the last date) and plots elevations for that specific time. 
But is there a way to extract the maximum elevation for each point during the entire timeseries and plot the maximum elevations for the domain?

**Comment by pmav99** [comment]
Yes it is possible. There are two ways actually:

Instead of a timestamp object, you can pass the string `"max"` to `create_trimesh()`. This way, [xr.Dataset.max()](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.max.html) will be used behind the scenes and you will get the maximum elevation. This is how you would use it:
``` python
create_trimesh(ds=ds, variable="elev", timestamp="max")
```

The other way is the manual approach, i.e. you "aggregate" the maximum elevation yourself, save it to a data variable and visualize that one instead. For example:

``` python
ds = ds.assign(elev_max=ds.elev.max("time"))
create_trimesh(ds=ds, variable="elev_max")
```

If you have a relatively small mesh, then the first approach is just fine. For meshes with many millions of nodes though, the second approach is probably better performance wise (you can do it in the post-processing step of your model, instead of when you visualize etc).

**Comment by FariborzDaneshvar-NOAA** [comment]
Thank you!

**Comment by pmav99** [comment]
Since version 0.4.0, the only supported way to visualize SCHISM's maximum elevation is to pre-calculate it using xarray. For example:

``` python
ds = thalassa.open_dataset("some_file_with_schism_output.nc")
ds["elev_max"] = ds.elev.max("time")
```

And the plot it with:
```
plot = thalassa.plot(ds, "elev_max")
plot
```
